tox: don't require yappi version
Recently, we stopped requireing pytest and pytest-cov versions in
commit

    commit e0fdd9f4878eb82ceb077f7fe20325232329fb47
    Author: Nir Soffer <nsoffer@redhat.com>
    Date:   Thu Dec 10 18:59:50 2020 +0200

	tox: Use latest pytest and pytest-cov

Don't require also yappi version, which is quite old and use the
latest one.

Also, this old version fails to compile e.g. on my FC 32
and FC 33:

    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIB_RT_AVAILABLE=1 -I/home/vjuranek/ovirt/vdsm/.tox/tests/include -I/usr/include/python3.8 -c _yappi.c -o build/temp.linux-x86_64-3.8/_yappi.o
      _yappi.c: In function ‘_enum_threads’:
      _yappi.c:800:39: error: invalid use of incomplete typedef ‘PyInterpreterState’ {aka ‘struct _is’}
	800 |     for (p=PyThreadState_GET()->interp->tstate_head ; p != NULL; p = p->next) {
	    |                                       ^~
      _yappi.c: In function ‘set_clock_type’:
      _yappi.c:1239:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘clock_type_t’ [-Wsign-compare]
       1239 |     if (clock_type == get_timing_clock_type())
	    |                    ^~
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
      ERROR: Failed building wheel for yappi
      Running setup.py clean for yappi
    Failed to build yappi

Change-Id: If4dbc09b9c0530b027a3d6ac5f06bfd6f4832ca6
Signed-off-by: Vojtech Juranek <vjuranek@redhat.com>